name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: UI
        run: npm install

      - name: Install Playwright browsers
        working-directory: UI
        run: npx playwright install --with-deps

      - name: Run login suite
        working-directory: UI
        env:
          BASE_URL: https://www.demoblaze.com/
          DEFAULT_TIMEOUT: 30000
          SLOW_MO: 0
        run: npx playwright test --project=login --workers=1

      - name: Run add_to_cart suite
        working-directory: UI
        env:
          BASE_URL: https://www.demoblaze.com/
          DEFAULT_TIMEOUT: 30000
          SLOW_MO: 0
        run: npx playwright test --project=add_to_cart --workers=1

      - name: Run firefox
        working-directory: UI
        env:
          BASE_URL: https://www.demoblaze.com/
          DEFAULT_TIMEOUT: 30000
          SLOW_MO: 0
        run: npx playwright test --project=firefox

      - name: Run webkit
        working-directory: UI
        env:
          BASE_URL: https://www.demoblaze.com/
          DEFAULT_TIMEOUT: 30000
          SLOW_MO: 0
        run: npx playwright test --project=webkit
